config/routes.rb
Rails.application.routes.draw do
  

  resources :food_items
  resources :categories
  
  #get 'sessions/new'
  get '/login',        to: 'sessions#new'
  post '/login',       to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  #get 'users/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/search',  to: 'users#search'
  get '/search',  to: 'users#search'
 
  resources :users

  #get 'fooditems/index'
  #get  '/show', to: 'food_items#index'
  
  #get 'restaurant_web/ home'
    

   root 'restaurant_web#home'
   get  '/contact', to: 'restaurant_web#contact'
   get  '/menu', to: 'category_list#select_category'
   get  '/add_category', to: 'categories#index'
   get  '/new_food_items', to: 'food_items#new'
   get  '/go_to_food_items', to: 'food_items#index'
   get  '/go_to_categories', to: 'categories#index'
   get '/selected_category', to: 'category_list#selected_category'
   get  '/list', to: 'category_list#list'
   get  '/create_order', to: 'category_list#create_order'
   
   

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
  belongs_to :category
  validates :name, :size, :price, presence: true
  validates :name, length: {maximum: 20}
  validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 10000}  

end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :size, :price, :category_id)
    end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-control-label' %>
    <%= form.text_field :name, id: :food_item_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :size, class: 'form-control-label' %>
    <%= form.number_field :size, id: :food_item_size, class: 'form-control'%>
  </div>

  <div class="form-group"
    <%= form.label :price, class: 'form-control-label'%>
    <%= form.text_field :price, id: :food_item_price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :category_id, class: 'form-control-label' %>
    <%= form.text_field :category_id, id: :food_item_category_id, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit"create new food item", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Manage Food Items<th></t>
    </tr>
    <tr>
      <th><%= link_to 'New Category', new_category_path, class: "btn btn-sm btn-primary"  %><th>
    </tr>
    <tr>
      <th><%= link_to 'New Food Item', new_food_item_path, class: "btn btn-sm btn-primary"  %><th>
    </tr>
  </thead>
</table>

<table class = "table tabel-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Price</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.size %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.category_id %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Go to Categories Page", go_to_categories_path, class: "btn btn btn-primary" %>
<br>
<br>
<%= link_to "Return to Menu", menu_path, class: "btn btn btn-primary" %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @food_item.size %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<div class="manager">
  <p>
    <strong>Category:</strong>
    <%= link_to @food_item.category.name, @food_item.category %>
  </p>
  <%= link_to 'Edit', edit_food_item_path(@food_item) %> |
  <%= link_to 'Back', food_items_path %>
</div>