config/routes.rb
Rails.application.routes.draw do
  

  resources :food_items
  resources :categories
  
  #get 'sessions/new'
  get '/login',        to: 'sessions#new'
  post '/login',       to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  #get 'users/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/search',  to: 'users#search'
  get '/search',  to: 'users#search'
 
  resources :users

  #get 'fooditems/index'
  #get  '/show', to: 'food_items#index'
  
  #get 'restaurant_web/ home'
    

   root 'restaurant_web#home'
   get  '/contact', to: 'restaurant_web#contact'
   get  '/menu', to: 'category_list#select_category'
   get  '/add_category', to: 'categories#index'
   get  '/new_food_items', to: 'food_items#new'
   get  '/go_to_food_items', to: 'food_items#index'
   get  '/go_to_categories', to: 'categories#index'
   get '/selected_category', to: 'category_list#selected_category'
   get  '/list', to: 'category_list#list'
   get  '/create_order', to: 'category_list#create_order'
   
   

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :food_items
  validates:name, presence: true 
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index,:show,:edit, :update]
  #before_action :correct_user,   only: [:show, :edit,:update]
 
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
    
    def logged_in_user

      unless logged_in?

       store_location

        flash[:danger] = "Please log in."

        redirect_to login_url

      end

    end

    # Confirms the correct user.

    def correct_user

      @user = User.find(params[:id])

      unless @user == current_user

        flash[:danger] = "You are not authorized to do that."

        redirect_to(root_url)

      end

    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: 'form-control-label' %>
    <%= form.text_field :name, id: :category_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Create new category", class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/categories/_selected_category.html.erb
<table>
    <strong>Displaying: <%= category.name %></strong>
    <% category.food_items.each do |food_item| %>
      <tr>
        <td><%= link_to food_item.name, food_item %></td>
        <td>$<%= food_item.price %></td>
      </tr>
    <% end %>
</table>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% provide(:title, "Menu") %>

<p id="notice"><%= notice %></p>



<h1>Menu</h1>


<table>

  <thead>

    <tr>

      <th>Manage Categories<th></t>

      <th colspan="3"></th>

    </tr>

    <tr>

      <th><%= link_to 'New Category', new_category_path, class: "btn btn-sm btn-primary"  %><th>

    </tr>

    <tr>

      <th><%= link_to 'New Item', new_food_item_path, class: "btn btn-sm btn-primary"  %><th>

    </tr>

  </thead>

<table class = "table tabel-striped">
  <thead class = "thead thead-default">
    <tr>
      <th>Name</th>
      <th>ID</th>
      <th>Amount of Items</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.id %></td>
        <td><%= category.food_items.size %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Go to Foods Page", go_to_food_items_path, class: "btn btn btn-primary" %>
<br>
<br>
<%= link_to "Return to Menu", menu_path, class: "btn btn btn-primary" %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/selected_category.js.erb
$('#foods').html('');
$("#foods").append("<%= escape_javascript("#{render :partial => 'categories/selected_category', :locals => {:category => @category }}").html_safe %>");

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<table>
    <strong>FoodItems:</strong>
    <% @category.food_items.each do |food_item| %>
      <tr>
        <td><%= link_to food_item.name, food_item %></td>
      </tr>
      <% end %>
</table>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>