config/routes.rb
Rails.application.routes.draw do
  

  resources :food_items
  resources :categories
  
  #get 'sessions/new'
  get '/login',        to: 'sessions#new'
  post '/login',       to: 'sessions#create'
  delete '/logout',    to: 'sessions#destroy'

  #get 'users/new'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  post '/search',  to: 'users#search'
  get '/search',  to: 'users#search'
 
  resources :users

  #get 'fooditems/index'
  #get  '/show', to: 'food_items#index'
  
  #get 'restaurant_web/ home'
    

   root 'restaurant_web#home'
   get  '/contact', to: 'restaurant_web#contact'
   get  '/menu', to: 'category_list#select_category'
   get  '/add_category', to: 'categories#index'
   get  '/new_food_items', to: 'food_items#new'
   get  '/go_to_food_items', to: 'food_items#index'
   get  '/go_to_categories', to: 'categories#index'
   get '/selected_category', to: 'category_list#selected_category'
   get  '/list', to: 'category_list#list'
   get  '/create_order', to: 'category_list#create_order'
   
   

 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/category_list_controller.rb
class CategoryListController < ApplicationController
  
  def list
    @category = Category.find(params[:id])
  end
  
  def create_order
    @category = Category.find(params[:id])
  end
  
  def select_category
    @categories = Category.all
  end
  
  def selected_category
    @category = Category.find(params[:id])
    render 'selected_category.js.erb'
  end
end

app/helpers/category_list_helper.rb
module CategoryListHelper
end

app/views/category_list/_selected_category.html.erb
<table>
    <strong>Displaying: <%= category.name %></strong>
    <% category.food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td>$<%= food_item.price %></td>
        <td><%= link_to 'Add To Order', create_order_path(@category, :id => @category.id), class: 'btn btn-primary'%></td>
      </tr>
    <% end %>
</table>

app/views/category_list/create_order.html.erb
<table>

    <strong>You have selected the following iems</strong>

    <% @category.food_items.each do |food_item| %>

      <tr>

        <td><%= food_item.name %></td>

        <td>$<%= food_item.price %></td>

      </tr>

    <% end %>

</table>
<%= link_to 'Back', categories_path, class: 'btn btn-primary'%>

app/views/category_list/list.html.erb
<table>

    <strong>Displaying: <%= @category.name %></strong>

    <% @category.food_items.each do |food_item| %>

      <tr>

        <td><%= link_to food_item.name, create_order_path(@category, :id => @category.id)%></td>

        <td>$<%= food_item.price %></td>

      </tr>

    <% end %>

</table>
<%= link_to 'Back', menu_path, class: 'btn btn-primary'%>

app/views/category_list/select_category.html.erb
<% provide(:title, "Menu") %>

<p id="notice"><%= notice %></p>



<h1>Menu</h1>

<div class="button-container">

  <div class="row">

    <% @categories.each do |category| %>

      <td id = '<%= category.id %>'>

        <span class = 'category-button'>

          <%= link_to category.name, selected_category_path(category, :id => category.id), remote: true, class: "btn btn-lg btn-primary" %>

        </spa>

      </td>

    <% end %>
    
  </div>
  
</div>


<section id="foods-section">

  <div id="foods">

  </div>

</section>

<br>
<br>
<%= link_to "Manage Menu", add_category_path, class: "btn btn-primary" %>

app/views/category_list/selected_category.js.erb
$('#foods').html('');
$("#foods").append("<%= escape_javascript("#{render :partial => 'category_list/selected_category', :locals => {:category => @category }}").html_safe %>");